#!/usr/bin/env bash
set -euo pipefail

OS=$(uname -s)
ARCH=$(uname -m)

if [[ "${OS}" != "Linux" ]]; then
    echo "Error: install.sh supports Linux only (detected ${OS})." >&2
    exit 1
fi
if [[ "${ARCH}" != "x86_64" ]]; then
    echo "Error: install.sh supports x86_64 only (detected ${ARCH})." >&2
    exit 1
fi
if ! command -v apt-get >/dev/null 2>&1; then
    echo "Error: apt-get is required." >&2
    exit 1
fi

ROOT_DIR=$(dirname "$(readlink -f "$0")")
SMT_PATH="${ROOT_DIR}/smts"
BAZELRC_PATH="${ROOT_DIR}/.bazelrc"

echo "[*] Updating Bazel configuration ..."
mkdir -p "${SMT_PATH}"
cat >"${BAZELRC_PATH}" <<EOF
# Automatically generated by install.sh
build --sandbox_writable_path=${SMT_PATH}/ \
      --action_env=SMT_DIRECTORY_PREFIX=${SMT_PATH}/ \
      --explicit_java_test_deps
EOF

TEMP_DIR=$(mktemp -d)
trap 'rm -rf "${TEMP_DIR}"' EXIT

BAZELISK_VERSION="1.25.0"
BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/v${BAZELISK_VERSION}/bazelisk-linux-amd64"

Z3_VERSION="4.14.0"
Z3_PLATFORM="x64-glibc-2.35"
Z3_BASENAME="z3-${Z3_VERSION}-${Z3_PLATFORM}"
Z3_URL="https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/${Z3_BASENAME}.zip"

echo "[*] Installing Linux dependencies ..."
sudo apt-get update
sudo apt-get install -y \
    ca-certificates \
    openjdk-11-jdk \
    python3 \
    rsync \
    unzip \
    wget

echo "[*] Installing Bazelisk ${BAZELISK_VERSION} ..."
wget -O "${TEMP_DIR}/bazelisk" "${BAZELISK_URL}"
sudo install -m 0755 "${TEMP_DIR}/bazelisk" /usr/local/bin/bazelisk
sudo ln -sf /usr/local/bin/bazelisk /usr/local/bin/bazel

echo "[*] Installing Z3 ${Z3_VERSION} ..."
wget -O "${TEMP_DIR}/${Z3_BASENAME}.zip" "${Z3_URL}"
unzip -q "${TEMP_DIR}/${Z3_BASENAME}.zip" -d "${TEMP_DIR}"
sudo install -m 0755 "${TEMP_DIR}/${Z3_BASENAME}/bin/z3" /usr/bin/z3
sudo install -m 0755 "${TEMP_DIR}/${Z3_BASENAME}/bin/libz3.so" /usr/lib/libz3.so
sudo install -m 0755 \
    "${TEMP_DIR}/${Z3_BASENAME}/bin/libz3java.so" \
    /usr/lib/libz3java.so
sudo install -m 0644 \
    "${TEMP_DIR}/${Z3_BASENAME}/bin/com.microsoft.z3.jar" \
    /usr/lib/com.microsoft.z3.jar
sudo rsync -a "${TEMP_DIR}/${Z3_BASENAME}/include/" /usr/include/

echo "[✓] Completed: Linux installation"
