#!/usr/bin/env bash
set -euo pipefail

OS=$(uname -s)
ARCH=$(uname -m)

if [[ "${OS}" == "Darwin" ]]; then
    if ! command -v greadlink >/dev/null 2>&1; then
        if ! command -v brew >/dev/null 2>&1; then
            echo "Error: Homebrew is required on macOS." >&2
            exit 1
        fi
        brew install coreutils
    fi
    ROOT_DIR=$(dirname "$(greadlink -f "$0")")
elif [[ "${OS}" == "Linux" ]]; then
    ROOT_DIR=$(dirname "$(readlink -f "$0")")
else
    echo "Error: install.sh supports Linux and macOS only (detected ${OS})." >&2
    exit 1
fi

SMT_PATH="${ROOT_DIR}/smts"
BAZELRC_PATH="${ROOT_DIR}/.bazelrc"

echo "Detected system: ${OS} (${ARCH})"

update_bazelrc_for_linux() {
    echo "[*] Updating Bazel configuration ..."
    mkdir -p "${SMT_PATH}"
    cat >"${BAZELRC_PATH}" <<EOF
# Automatically generated by install.sh
build --sandbox_writable_path=${SMT_PATH}/ \
      --action_env=SMT_DIRECTORY_PREFIX=${SMT_PATH}/ \
      --explicit_java_test_deps
EOF
}

update_bazelrc_for_macos() {
    echo "[*] Updating Bazel configuration for macOS ..."
    mkdir -p "${SMT_PATH}"
    Z3_JAVA_EXTENSIONS="${HOME}/Library/Java/Extensions"
    cat >"${BAZELRC_PATH}" <<EOF
# Automatically generated by install.sh (macOS)
build --sandbox_writable_path=${SMT_PATH}/ \
      --action_env=SMT_DIRECTORY_PREFIX=${SMT_PATH}/ \
      --explicit_java_test_deps

# Z3 JNI: run tests outside sandbox; load libs from Java Extensions
test --strategy=TestRunner=standalone
test --spawn_strategy=local
test --test_env=JAVA_TOOL_OPTIONS=-Djava.library.path=${Z3_JAVA_EXTENSIONS}
EOF
}

install_for_linux() {
    if [[ "${ARCH}" != "x86_64" ]]; then
        echo "Error: Linux installation supports x86_64 only (detected ${ARCH})." >&2
        exit 1
    fi
    if ! command -v apt-get >/dev/null 2>&1; then
        echo "Error: apt-get is required." >&2
        exit 1
    fi

    TEMP_DIR=$(mktemp -d)
    trap 'rm -rf "${TEMP_DIR}"' EXIT

    BAZELISK_VERSION="1.25.0"
    BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/v${BAZELISK_VERSION}/bazelisk-linux-amd64"

    Z3_VERSION="4.14.0"
    Z3_PLATFORM="x64-glibc-2.35"
    Z3_BASENAME="z3-${Z3_VERSION}-${Z3_PLATFORM}"
    Z3_URL="https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/${Z3_BASENAME}.zip"

    echo "[*] Installing Linux dependencies ..."
    sudo apt-get update
    sudo apt-get install -y \
        ca-certificates \
        openjdk-11-jdk \
        python3 \
        python3-pip \
        rsync \
        unzip \
        wget

    echo "[*] Installing Bazelisk ${BAZELISK_VERSION} ..."
    wget -O "${TEMP_DIR}/bazelisk" "${BAZELISK_URL}"
    sudo install -m 0755 "${TEMP_DIR}/bazelisk" /usr/local/bin/bazelisk
    sudo ln -sf /usr/local/bin/bazelisk /usr/local/bin/bazel

    echo "[*] Installing Z3 ${Z3_VERSION} ..."
    wget -O "${TEMP_DIR}/${Z3_BASENAME}.zip" "${Z3_URL}"
    unzip -q "${TEMP_DIR}/${Z3_BASENAME}.zip" -d "${TEMP_DIR}"
    sudo install -m 0755 "${TEMP_DIR}/${Z3_BASENAME}/bin/z3" /usr/bin/z3
    sudo install -m 0755 "${TEMP_DIR}/${Z3_BASENAME}/bin/libz3.so" /usr/lib/libz3.so
    sudo install -m 0755 \
        "${TEMP_DIR}/${Z3_BASENAME}/bin/libz3java.so" \
        /usr/lib/libz3java.so
    sudo install -m 0644 \
        "${TEMP_DIR}/${Z3_BASENAME}/bin/com.microsoft.z3.jar" \
        /usr/lib/com.microsoft.z3.jar
    sudo rsync -a "${TEMP_DIR}/${Z3_BASENAME}/include/" /usr/include/

    echo "[*] Installing Jupyter Notebook ..."
    sudo pip3 install notebook

    echo "[✓] Completed: Linux installation"
}

install_for_macos() {
    if [[ "${ARCH}" != "arm64" ]]; then
        echo "Error: macOS installation supports arm64 only (detected ${ARCH})." >&2
        exit 1
    fi

    TEMP_DIR=$(mktemp -d)
    trap 'rm -rf "${TEMP_DIR}"' EXIT

    Z3_VERSION="4.14.0"
    Z3_PLATFORM="arm64-osx-13.7.2"
    Z3_BASENAME="z3-${Z3_VERSION}-${Z3_PLATFORM}"
    Z3_URL="https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/${Z3_BASENAME}.zip"
    Z3_BIN_DIR="/usr/local/bin"
    Z3_INCLUDE_DIR="/usr/local/include"
    Z3_LIB_DIR="/usr/local/lib"

    echo "[*] Installing macOS dependencies ..."

    if ! command -v brew >/dev/null 2>&1; then
        echo "[*] Homebrew not found. Installing Homebrew ..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    echo "[*] Installing OpenJDK 11 ..."
    brew install openjdk@11
    JAVA_HOME="$(brew --prefix openjdk@11)/libexec/openjdk.jdk/Contents/Home"
    export PATH="${JAVA_HOME}/bin:${PATH}"
    echo "export JAVA_HOME=${JAVA_HOME}" >>"${HOME}/.zshrc"
    echo "export JAVA_HOME=${JAVA_HOME}" >>"${HOME}/.bashrc"

    echo "[*] Installing wget ..."
    brew install wget

    echo "[*] Installing Python 3 ..."
    brew install python3

    echo "[*] Installing Bazelisk ..."
    brew install bazelisk
    brew link --overwrite bazelisk

    echo "[*] Installing Z3 ${Z3_VERSION} ..."
    wget -O "${TEMP_DIR}/${Z3_BASENAME}.zip" "${Z3_URL}"
    unzip -q "${TEMP_DIR}/${Z3_BASENAME}.zip" -d "${TEMP_DIR}"
    sudo install -m 0755 "${TEMP_DIR}/${Z3_BASENAME}/bin/z3" "${Z3_BIN_DIR}/z3"
    sudo install -m 0755 "${TEMP_DIR}/${Z3_BASENAME}/bin/libz3.dylib" "${Z3_LIB_DIR}/libz3.dylib"
    sudo install -m 0755 \
        "${TEMP_DIR}/${Z3_BASENAME}/bin/libz3java.dylib" \
        "${Z3_LIB_DIR}/libz3java.dylib"
    sudo install -m 0644 \
        "${TEMP_DIR}/${Z3_BASENAME}/bin/com.microsoft.z3.jar" \
        "${Z3_LIB_DIR}/com.microsoft.z3.jar"
    sudo rsync -a "${TEMP_DIR}/${Z3_BASENAME}/include/" "${Z3_INCLUDE_DIR}/"

    echo "[*] Configuring Z3 JNI for macOS ..."
    mkdir -p "${HOME}/Library/Java/Extensions"
    cp -f "${Z3_LIB_DIR}/libz3.dylib" "${Z3_LIB_DIR}/libz3java.dylib" \
        "${HOME}/Library/Java/Extensions/"
    install_name_tool -change libz3.dylib @loader_path/libz3.dylib \
        "${HOME}/Library/Java/Extensions/libz3java.dylib"
    sudo install_name_tool -change libz3.dylib @loader_path/libz3.dylib \
        "${Z3_LIB_DIR}/libz3java.dylib"
    if [[ -x "${ROOT_DIR}/tools/fix_z3_macos_gatekeeper.sh" ]]; then
        "${ROOT_DIR}/tools/fix_z3_macos_gatekeeper.sh" || true
    fi

    echo "[*] Installing Jupyter Notebook ..."
    sudo pip3 install notebook

    echo "[✓] Completed: macOS installation"
}

case "${OS}" in
    Linux)
        update_bazelrc_for_linux
        install_for_linux
        ;;
    Darwin)
        update_bazelrc_for_macos
        install_for_macos
        ;;
    *)
        echo "Error: Unsupported system: ${OS}" >&2
        exit 1
        ;;
esac

echo "[✓] All done!"
