#!/usr/bin/env python3
"""Plot one scalability experiment generated by the artifact runners."""

import argparse
import csv
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from utils.scalability import (
    ALL_STEP_KEYS,
    FATTREE_TO_DEVICES,
    TIMEOUT_SEC,
    plot_line_chart,
)


TOKEN_RE = re.compile(r"(\d+(?:\.\d+)?)(h|min|m|s)")
DATASETS = {
    "fattrees": (r"fattree(\d+)", "Device(s)", "fig-scalability-fattrees"),
    "lines": (r"line(\d+)", "Configuration Line(s)", "fig-scalability-lines"),
    "threads": (r"thread(\d+)", "Core(s)", "fig-scalability-threads"),
}


def parse_duration(value, timeout):
    value = (value or "").strip()
    if not value or value.endswith("+") or value.upper() == "ERROR":
        return timeout
    compact = value.replace(" ", "")
    tokens = TOKEN_RE.findall(compact)
    if not tokens or "".join(number + unit for number, unit in tokens) != compact:
        return timeout
    units = {"h": 3600, "min": 60, "m": 60, "s": 1}
    return sum(float(number) * units[unit] for number, unit in tokens)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--dataset", required=True, choices=DATASETS)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--timeout-seconds", required=True, type=float)
    parser.add_argument("--mode", required=True, choices=("fast", "full"))
    args = parser.parse_args()

    pattern, xlabel, stem = DATASETS[args.dataset]
    by_x = {}
    with args.input.open(newline="") as stream:
        for row in csv.DictReader(stream):
            if row.get("benchmark", "").lower() != args.dataset:
                continue
            match = re.search(pattern, row.get("case", ""), re.I)
            if match is None:
                continue
            raw_x = match.group(1)
            x_value = (
                FATTREE_TO_DEVICES.get(raw_x)
                if args.dataset == "fattrees"
                else int(raw_x)
            )
            if x_value is None:
                continue
            by_x[x_value] = {
                step: parse_duration(row.get(step), args.timeout_seconds)
                for step in ALL_STEP_KEYS
            }

    if not by_x:
        raise SystemExit(f"No {args.dataset} rows found in {args.input}")
    x_values = sorted(by_x)
    series = {
        step: [by_x[x_value][step] for x_value in x_values]
        for step in ALL_STEP_KEYS
    }
    args.output_dir.mkdir(parents=True, exist_ok=True)
    output_path = args.output_dir / stem
    if args.mode == "full":
        plot_line_chart(x_values, series, xlabel, output_path)
        return

    prep = np.array([
        sum(series[step][index] for step in ("step1.0", "step1.1", "step1.2", "step1.3"))
        for index in range(len(x_values))
    ])

    def workflow(first, second, include_preparation):
        values = []
        timeouts = []
        for index in range(len(x_values)):
            first_value = series[first][index]
            second_value = series[second][index]
            timed_out = (
                first_value >= args.timeout_seconds
                or second_value >= args.timeout_seconds
            )
            total = args.timeout_seconds if timed_out else first_value + second_value
            if include_preparation and not timed_out:
                total += prep[index]
            values.append(min(total, args.timeout_seconds) / 60)
            timeouts.append(timed_out)
        return np.array(values), np.array(timeouts)

    workflows = (
        ("NoScope", *workflow("step3.1", "step3.2", True), "#2FA18C", "^"),
        ("FullSym", *workflow("step4.1", "step4.2", False), "#5B9BD5", "s"),
        ("SubSpec", *workflow("step2.1", "step2.2", True), "#F2994A", "o"),
    )
    positions = np.arange(len(x_values))
    figure, axis = plt.subplots(figsize=(8, 5.2), constrained_layout=True)
    for label, values, timeouts, color, marker in workflows:
        axis.plot(
            positions,
            values,
            color=color,
            marker=marker,
            markersize=9,
            linewidth=2.2,
            markerfacecolor="white",
            markeredgewidth=1.8,
            label=label,
        )
        for x_value, y_value, timed_out in zip(positions, values, timeouts):
            if timed_out:
                axis.annotate(
                    "TO",
                    (x_value, y_value),
                    xytext=(0, 7),
                    textcoords="offset points",
                    ha="center",
                    fontsize=8,
                    fontweight="bold",
                )
    axis.axhline(
        args.timeout_seconds / 60,
        color="#444444",
        linestyle="--",
        linewidth=0.9,
    )
    axis.set_xticks(positions, [str(value) for value in x_values])
    axis.set_xlabel(xlabel)
    axis.set_ylabel("Time (minutes)")
    axis.set_title("Scalability reproduction (fast)")
    axis.grid(axis="y", color="#dddddd", linewidth=0.7)
    axis.legend(frameon=False, ncol=3)
    figure.savefig(output_path.with_suffix(".png"), dpi=220, bbox_inches="tight")
    figure.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")


if __name__ == "__main__":
    main()
